/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAttentionRouteImport } from './routes/_app/attention'
import { Route as AppGapsRouteImport } from './routes/_app/gaps'
import { Route as AppIssuesRouteImport } from './routes/_app/issues'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppPostsalesRouteImport } from './routes/_app/postsales'
import { Route as AppPresalesRouteImport } from './routes/_app/presales'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountsIdRouteImport } from './routes/_app/accounts/$id'
import { Route as AppEngagementsIdRouteImport } from './routes/_app/engagements/$id'
import { Route as AppThreadsIndexRouteImport } from './routes/_app/threads/index'
import { Route as AppThreadsIdRouteImport } from './routes/_app/threads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAttentionRoute = AppAttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => AppRoute,
} as any)
const AppGapsRoute = AppGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsalesRoute = AppPostsalesRouteImport.update({
  id: '/postsales',
  path: '/postsales',
  getParentRoute: () => AppRoute,
} as any)
const AppPresalesRoute = AppPresalesRouteImport.update({
  id: '/presales',
  path: '/presales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEngagementsIdRoute = AppEngagementsIdRouteImport.update({
  id: '/engagements/$id',
  path: '/engagements/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsIndexRoute = AppThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsIdRoute = AppThreadsIdRouteImport.update({
  id: '/threads/$id',
  path: '/threads/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/attention': typeof AppAttentionRoute
  '/gaps': typeof AppGapsRoute
  '/issues': typeof AppIssuesRoute
  '/metrics': typeof AppMetricsRoute
  '/postsales': typeof AppPostsalesRoute
  '/presales': typeof AppPresalesRoute
  '/settings': typeof AppSettingsRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/engagements/$id': typeof AppEngagementsIdRoute
  '/threads/$id': typeof AppThreadsIdRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/threads/': typeof AppThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/attention': typeof AppAttentionRoute
  '/gaps': typeof AppGapsRoute
  '/issues': typeof AppIssuesRoute
  '/metrics': typeof AppMetricsRoute
  '/postsales': typeof AppPostsalesRoute
  '/presales': typeof AppPresalesRoute
  '/settings': typeof AppSettingsRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/engagements/$id': typeof AppEngagementsIdRoute
  '/threads/$id': typeof AppThreadsIdRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/threads': typeof AppThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/attention': typeof AppAttentionRoute
  '/_app/gaps': typeof AppGapsRoute
  '/_app/issues': typeof AppIssuesRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/postsales': typeof AppPostsalesRoute
  '/_app/presales': typeof AppPresalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/accounts/$id': typeof AppAccountsIdRoute
  '/_app/engagements/$id': typeof AppEngagementsIdRoute
  '/_app/threads/$id': typeof AppThreadsIdRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/threads/': typeof AppThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/attention'
    | '/gaps'
    | '/issues'
    | '/metrics'
    | '/postsales'
    | '/presales'
    | '/settings'
    | '/accounts/$id'
    | '/engagements/$id'
    | '/threads/$id'
    | '/accounts/'
    | '/threads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/attention'
    | '/gaps'
    | '/issues'
    | '/metrics'
    | '/postsales'
    | '/presales'
    | '/settings'
    | '/accounts/$id'
    | '/engagements/$id'
    | '/threads/$id'
    | '/accounts'
    | '/threads'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/attention'
    | '/_app/gaps'
    | '/_app/issues'
    | '/_app/metrics'
    | '/_app/postsales'
    | '/_app/presales'
    | '/_app/settings'
    | '/_app/accounts/$id'
    | '/_app/engagements/$id'
    | '/_app/threads/$id'
    | '/_app/accounts/'
    | '/_app/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/attention': {
      id: '/_app/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AppAttentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gaps': {
      id: '/_app/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AppGapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues': {
      id: '/_app/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/postsales': {
      id: '/_app/postsales'
      path: '/postsales'
      fullPath: '/postsales'
      preLoaderRoute: typeof AppPostsalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presales': {
      id: '/_app/presales'
      path: '/presales'
      fullPath: '/presales'
      preLoaderRoute: typeof AppPresalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$id': {
      id: '/_app/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engagements/$id': {
      id: '/_app/engagements/$id'
      path: '/engagements/$id'
      fullPath: '/engagements/$id'
      preLoaderRoute: typeof AppEngagementsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/': {
      id: '/_app/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof AppThreadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/$id': {
      id: '/_app/threads/$id'
      path: '/threads/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof AppThreadsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttentionRoute: typeof AppAttentionRoute
  AppGapsRoute: typeof AppGapsRoute
  AppIssuesRoute: typeof AppIssuesRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppPostsalesRoute: typeof AppPostsalesRoute
  AppPresalesRoute: typeof AppPresalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAccountsIdRoute: typeof AppAccountsIdRoute
  AppEngagementsIdRoute: typeof AppEngagementsIdRoute
  AppThreadsIdRoute: typeof AppThreadsIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppThreadsIndexRoute: typeof AppThreadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttentionRoute: AppAttentionRoute,
  AppGapsRoute: AppGapsRoute,
  AppIssuesRoute: AppIssuesRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppPostsalesRoute: AppPostsalesRoute,
  AppPresalesRoute: AppPresalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAccountsIdRoute: AppAccountsIdRoute,
  AppEngagementsIdRoute: AppEngagementsIdRoute,
  AppThreadsIdRoute: AppThreadsIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppThreadsIndexRoute: AppThreadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
